version: "2.0"
services:
  db:
    image: postgres:10.4-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=normalizer

  api:
    image: normalizer
    links:
    - db
    depends_on:
    - db